version: "3.9"

services:
  mongo:
    image: mongo:6.0.4
    environment:
      MONGO_INITDB_ROOT_USERNAME: dev
      MONGO_INITDB_ROOT_PASSWORD: password
    restart: on-failure

  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/artefact:/code/artefact
      - ./backend/config:/code/config
      - ./backend/tests:/code/tests
      - ./backend/manage.py:/code/manage.py
      - ./backend/pytest.ini:/code/pytest.ini
    environment:
      - MONGODB_CONN=mongodb://dev:password@mongo:27017/
      - MONGODB_DATABASE_NAME=artefact
      - MONGODB_COLLECTION=news_articles
    depends_on:
      - mongo
    restart: on-failure
