version: "3.9"

services:
  mongo:
    image: mongo:6.0.4
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: dev
      MONGO_INITDB_ROOT_PASSWORD: password

  crawlers:
    build: ./crawlers
    working_dir: /code/news_websites
    command: scrapy crawl bbc
    volumes:
      - ./crawlers/news_websites:/code/news_websites
      - ./crawlers/scrapy.cfg:/code/scrapy.cfg
    environment:
      - MONGODB_CONN=mongodb://dev:password@mongo:27017/
      - MONGODB_DATABASE_NAME=artefact
      - MONGODB_COLLECTION=news_articles
    depends_on:
      - mongo

  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/artefact:/code/artefact
      - ./backend/config:/code/config
      - ./backend/manage.py:/code/manage.py
    ports:
      - 8000:8000
    environment:
      - MONGODB_CONN=mongodb://dev:password@mongo:27017/
      - MONGODB_DATABASE_NAME=artefact
      - MONGODB_COLLECTION=news_articles
    depends_on:
      - mongo
      - crawlers
