version: "3.9"

services:
  crawlers:
    build: ./crawlers
    working_dir: /code/news_websites
    command: scrapy crawl bbc
    volumes:
      - ./crawlers/news_websites:/code/news_websites
      - ./crawlers/scrapy.cfg:/code/scrapy.cfg
    environment:
      - MONGODB_CONN=mongodb://dev:password@mongo:27017/
      - MONGODB_DATABASE_NAME=artefact
      - MONGODB_COLLECTION=news_articles
    depends_on:
      - mongo

  backend:
    ports:
      - 8000:8000
